# Generated by Django 5.0.5 on 2024-06-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_carmechanic"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="status_paid",
            field=models.CharField(choices=[("UP", "Unpaid"), ("P", "Paid")], max_length=2, null=True),
        ),
    ]
